### PR TITLE
Fix Number numeric attribute plan modifier failed error on 3.4.0

### LINKED ISSUE #299: Number numeric attribute plan modifier failed error on 3.4.0
### Terraform CLI and Provider Versions

- random provider version 3.4.0
- Terraform v1.1.0

### Terraform Configuration

```terraform
resource "random_password" "password" {
  length           = 16
  override_special = "_%$!"
}
```

### Expected Behavior

No changes are detected to the previously created random password resource.

### Actual Behavior

```
Error: Number numeric attribute plan modifier failed
│ 
│   with module.app_db.random_password.password,
│   on ../../../../infrastructure/rds/rds.tf line 1, in resource "random_password" "password":
│    1: resource "random_password" "password" {
│ 
│ Cannot specify both number and numeric in config
```

The following error is received as part of the plan

### Steps to Reproduce

1. Install latest version of the `random` provider
2. `terraform apply`

### How much impact is this issue causing?

Medium

### Logs

_No response_

### Additional Information

Reverting back to v3.3.2 resolves the issues.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bendbennett**
This should address #299 insofar as it fixes the issue when using the [config supplied](https://github.com/hashicorp/terraform-provider-random/issues/299#issuecomment-1232321922) by @NJITman.

### CODE REVIEW

File: internal/planmodifiers/attribute.go [hunk 1]
```diff
@@ -117,10 +117,10 @@ func (d *numberNumericAttributePlanModifier) Modify(ctx context.Context, req tfs
 		return
 	}
 
-	if !numberConfig.Null && !numericConfig.Null {
+	if !numberConfig.Null && !numericConfig.Null && (numberConfig.Value != numericConfig.Value) {
 		resp.Diagnostics.AddError(
-			"Number numeric attribute plan modifier failed",
-			"Cannot specify both number and numeric in config",
+			"Number and numeric are both present and have different values",
```
Comment (bflad) [inline internal/planmodifiers/attribute.go:122]: Tiny nit to avoid "and" twice 😄 

```suggestion
			"Number and numeric are both configured with different values",
```

File: internal/provider/resource_password_test.go [hunk 2]
```diff
@@ -710,3 +710,19 @@ func TestUpgradePasswordStateV1toV2(t *testing.T) {
...
+	resource.UnitTest(t, resource.TestCase{
+		ProtoV5ProviderFactories: protoV5ProviderFactories(),
+		Steps: []resource.TestStep{
+			{
+				Config: `resource "random_password" "number_numeric_differ" {
+  							length = 1
+							number = false
+  							numeric = true
+						}`,
+				ExpectError: regexp.MustCompile(`.*Number and numeric are both present and have different values`),
```
Comment (bflad) [inline internal/provider/resource_password_test.go:724]: With other change:

```suggestion
				ExpectError: regexp.MustCompile(`.*Number and numeric are both configured with different values`),
```

**Review by bflad — APPROVED** [review]
Looks good to me 🚀
