### PR TITLE
resource/random_password+random_string: Prevent override_special differences upgrading from 3.3.2

### LINKED ISSUE #306: random_password Showing Unexpected Plan 3.3.2 to 3.4.2
### Terraform CLI and Provider Versions

Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random v3.4.2

### Terraform Configuration

```terraform
terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "3.4.2"
      # version = "3.3.2"
    }
  }
}

resource "random_password" "test" {
  length = 20
}
```

### Expected Behavior

No plan difference.

### Actual Behavior

```console
$ terraform apply        
random_password.test: Refreshing state... [id=none]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # random_password.test will be updated in-place
  ~ resource "random_password" "test" {
        id          = "none"
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

### Logs

_No response_

### Additional Information

May be related to small change in #305 where `override_special` was having issues with framework migration testing and the fix seemed to be adding a default value plan modifier of `types.String{Value: ""}`. Here's the state difference after the odd plan output:

```diff
4c4
<   "serial": 1,
---
>   "serial": 3,
28c28
<             "override_special": null,
---
>             "override_special": "",
33,34c33
<           "sensitive_attributes": [],
<           "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjIifQ=="
---
>           "sensitive_attributes": []
```

Potentially removing `Computed` and removing the default value plan modifier can fix this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bflad**
Closes #306
Builds on #308 

_Note: This was almost completed work from Friday, but I didn't have time to submit it. We should compare and contrast this with #310, which I'll take a look at now._

This fixes the `override_special` attribute issues by removing `Computed: true` and the empty string default value plan modifier (this attribute's value should always come from the practitioner) and resolves the underlying issue of always reading `plan.OverrideSpecial.Value` into the state, which will never be correct for null configurations.

For any environment that happened to upgrade to 3.4.2 and save the empty string into state, the replacement plan modifier will allow in-place modification from empty string (`""`) to `null`.

Previously after removing `Computed: true` and default value plan modifier:

```
=== CONT  TestAccResourcePassword_OverrideSpecial_FromVersion3_3_2
    resource_password_test.go:221: Step 2/2 error: Error running apply: exit status 1

        Error: Provider produced inconsistent result after apply

        When applying changes to random_password.test, provider
        "provider[\"registry.terraform.io/hashicorp/random\"]" produced an unexpected
        new value: .override_special: was null, but now cty.StringVal("").

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
=== CONT  TestAccResourcePassword_OverrideSpecial_FromVersion3_4_2
    resource_password_test.go:255: Step 2/2 error: Error running apply: exit status 1

        Error: Provider produced inconsistent result after apply

        When applying changes to random_password.test, provider
        "provider[\"registry.terraform.io/hashicorp/random\"]" produced an unexpected
        new value: .override_special: was null, but now cty.StringVal("").

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

Previously before adjusting requires replace plan modifier:

```
=== CONT  TestAccResourcePassword_OverrideSpecial_FromVersion3_3_2
    resource_password_test.go:221: Step 2/2 error: Check failed: Check 3/3 error: attribute values are different, got :i$(*K3_Vinv and FSw{$8sB#Uc3
=== CONT  TestAccResourcePassword_OverrideSpecial_FromVersion3_4_2
    resource_password_test.go:255: Step 2/2 error: Check failed: Check 3/3 error: attribute values are different, got VrNYb]{#Z2Xu and XZD#_<BjDhkH
```

### CODE REVIEW

File: internal/provider/resource_password_test.go [hunk 1]
```diff
@@ -211,6 +211,74 @@ func TestAccResourcePassword_Override(t *testing.T) {
...
+// when upgrading the provider version from 3.3.2, which set the
+// override_special value to null and should not result in a plan difference.
+// Reference: https://github.com/hashicorp/terraform-provider-random/issues/306
+func TestAccResourcePassword_OverrideSpecial_FromVersion3_3_2(t *testing.T) {
+	var result1, result2 string
+
+	resource.ParallelTest(t, resource.TestCase{
+		Steps: []resource.TestStep{
+			{
+				ExternalProviders: providerVersion342(),
```
Comment (bendbennett) [inline internal/provider/resource_password_test.go:224]:
```suggestion
				ExternalProviders: providerVersion332(),
```

File: internal/provider/resource_password_test.go [hunk 2]
```diff
@@ -211,6 +211,74 @@ func TestAccResourcePassword_Override(t *testing.T) {
...
+				Config: `resource "random_password" "test" {
+							length = 12
+						}`,
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr("random_password.test", "override_special", ""),
```
Comment (bendbennett) [inline internal/provider/resource_password_test.go:229]:
```suggestion
					resource.TestCheckNoResourceAttr("random_password.test", "override_special"),
```

File: internal/provider/resource_string_test.go [hunk 3]
```diff
@@ -793,6 +793,74 @@ func TestAccResourceString_Override(t *testing.T) {
...
+// when upgrading the provider version from 3.3.2, which set the
+// override_special value to null and should not result in a plan difference.
+// Reference: https://github.com/hashicorp/terraform-provider-random/issues/306
+func TestAccResourceString_OverrideSpecial_FromVersion3_3_2(t *testing.T) {
+	var result1, result2 string
+
+	resource.ParallelTest(t, resource.TestCase{
+		Steps: []resource.TestStep{
+			{
+				ExternalProviders: providerVersion342(),
```
Comment (bendbennett) [inline internal/provider/resource_string_test.go:806]:
```suggestion
				ExternalProviders: providerVersion332(),
```

File: internal/provider/resource_string_test.go [hunk 4]
```diff
@@ -793,6 +793,74 @@ func TestAccResourceString_Override(t *testing.T) {
...
+				Config: `resource "random_string" "test" {
+							length = 12
+						}`,
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr("random_string.test", "override_special", ""),
```
Comment (bendbennett) [inline internal/provider/resource_string_test.go:811]:
```suggestion
					resource.TestCheckNoResourceAttr("random_string.test", "override_special"),
```

**Review by bendbennett — APPROVED** [review]
Nice!

Couple of minor updates to the tests for `v3.3.2`.
